version: '3.8'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./backend:/var/www
      - ./backend/_docker/nginx/conf.d/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 5555:80
    depends_on:
      - app
    container_name: app_nginx
    networks:
      - app_network

  nodejs:
    build:
      context: ./
      dockerfile: /frontend/_docker/app/Dockerfile
    container_name: app_node
    environment:
      - VUE_APP_API_URL=http://localhost:5555
    ports:
      - 8080:8080
    depends_on:
      - app
    networks:
      - app_network

  app:
    build:
      context: ./backend
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./backend:/var/www
    depends_on:
      - db
    container_name: app
    networks:
      - app_network

  db:
    image: mysql:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: monro
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 5353:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: app_db
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
